### ISSUE TITLE
Errors in latest tagged release

### ISSUE THREAD

**Issue by mallardduck** [codeat3/blade-file-icons#3]
Hiya,

This line is an example where the current tagged release is an error, but the master branch is correct.
In this case, the issue is missing `viewport`:
https://github.com/codeat3/blade-file-icons/blob/9a275c478eeb9a356f56d896569320f52f5cbd42/resources/svg/php.svg#L1

It appears that the `1.4.1` tag was created on `Jun 7` but the issue was fixed in #1 . So I think just tagging a new release should fix this issue (and likely others).

**Comment by swapnilsarwe** [comment]
Thanks for pointing out. 
Issue has been resolved and is tagged under tag [#1.5.1](https://github.com/codeat3/blade-file-icons/releases/tag/1.5.1)
